name: anime_list
description: A anime and manga application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.2-alpha+8

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  retrofit: '>=4.0.0 <5.0.0'
  dio: ^5.3.2
  awesome_dio_interceptor: ^1.0.0
  connectivity_plus: ^5.0.0

  # ui
  cupertino_icons: ^1.0.2
  auto_route: 7.0.0
  flutter_native_splash: any
  carousel_slider: ^4.2.1

  # dependency
  get_it: any

  # state management
  flutter_bloc: ^8.1.3

  # data
  equatable: ^2.0.5

  # firebase
  firebase_core: any
  firebase_crashlytics: any
 
dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  auto_route_generator: any
  floor_generator: ^1.4.2
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: ^2.2.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0
  test: any
  mockito: 5.4.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/jikan_moe_icon.png"

flutter_native_splash:
  color: "#792C2C"
  image: assets/images/jikan_moe_icon.png
  android_12:
    image: assets/images/jikan_moe_icon.png
    color: "#792C2C"
    icon_background_color: "#eeeeee"

  fullscreen: true